apiVersion: v1
kind: Pod
metadata:
  name: catalogo-de-produtos-pod
  labels:
    app: catalogo-de-produtos-pod
spec:
  containers:
    - name:  catalogo-de-produtos
      image: forketyfork/catalogodeprodutos
      imagePullPolicy: Never
      ports:
        - containerPort: 9999
  restartPolicy: Never