apiVersion: v1
kind: Pod
metadata:
  name: db-catalogo-de-produtos
  labels:
    app: db-catalogo-de-produtos
spec:
  containers:
    - name: db-catalogo-de-produtos
      image: mysql:5.7
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap