apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-catalogodeprodutos
spec:
  template:
    metadata:
      name: pod-catalogodeprodutos
      labels:
        app: pod-catalogodeprodutos
    spec:
      containers:
        - name:  catalogodeprodutos
          image: forketyfork/catalogodeprodutos
          imagePullPolicy: Never
          ports:
            - containerPort: 9999
          envFrom:
            - configMapRef:
                name: db-configmap
  replicas: 3
  selector:
    matchLabels:
      app: pod-catalogodeprodutos