apiVersion: v1
kind: Service
metadata:
  name: svc-node-port-catalogodeprodutos
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9999
      nodePort: 30000
  selector:
    app: catalogo-de-produtos-pod
