apiVersion: v1
kind: Service
metadata:
  name:  svc-cluster-ip-catalogodeprodutos
spec:
  type:  ClusterIP
  selector:
    app: catalogo-de-produtos-pod
  ports:
    - port: 9000
      targetPort: 9999