apiVersion: v1
kind: Service
metadata:
  name:  svc-load-balancer-catalogodeprodutos
spec:
  type:  LoadBalancer
  selector:
    app: pod-catalogodeprodutos
  ports:
    - port: 9000
      targetPort: 9999
      nodePort: 30001